import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { configured, supabase } from '../services/supabase'
import { exportRegistrations } from '../utils/exportRegistrations'
export default function Dashboard() {
  const [profile,setProfile]=useState(null), [registrations,setRegistrations]=useState([]), [events,setEvents]=useState([]), [message,setMessage]=useState('')
  useEffect(()=>{ if(!configured)return; (async()=>{ const {data:{user}}=await supabase.auth.getUser(); if(!user)return; const {data:p}=await supabase.from('profiles').select('*').eq('id',user.id).single(); setProfile(p); const {data:r}=await supabase.from('registrations').select('*, event:events(title,start_time)').eq('participant_id',user.id).order('registered_at',{ascending:false});setRegistrations(r||[]);if(['college_admin','organizer','core_team','super_admin'].includes(p?.role)){let q=supabase.from('events').select('*').order('created_at',{ascending:false});if(p.role==='organizer')q=q.eq('organizer_id',user.id);const {data}=await q;setEvents(data||[])}})() },[])
  if(!configured)return <section className="empty"><h1>Your dashboard</h1><p>Connect Supabase to sign in and view your activity.</p></section>
  if(!profile)return <p>Loading dashboard...</p>
  const manager=['college_admin','organizer','core_team','super_admin'].includes(profile.role)
  return <section><p className="eyebrow">DASHBOARD</p><div className="section-title"><div><h1>Hello, {profile.full_name||'there'}.</h1><p className="muted">Role: <span className="pill">{profile.role.replace('_',' ')}</span></p><p className="member-code">My member code: <strong>{profile.access_code||'Run the college registration upgrade SQL'}</strong></p></div>{manager&&<Link className="button" to="/create-event">Create event</Link>}</div><h2>My registrations</h2>{registrations.length?<Table registrations={registrations}/>:<p className="muted">You have not registered for any events.</p>}{manager&&<><h2>Managed events</h2>{events.length?<div className="table"><table><thead><tr><th>Event</th><th>Status</th><th>Deadline</th><th>Data</th></tr></thead><tbody>{events.map(event=><tr key={event.id}><td>{event.title}</td><td><span className="pill">{event.status}</span></td><td>{event.registration_deadline?new Date(event.registration_deadline).toLocaleString():'None'}</td><td><button onClick={async()=>{try{await exportRegistrations(event.id,event.title)}catch(e){setMessage(e.message)}}}>Export Excel</button></td></tr>)}</tbody></table></div>:<p className="muted">No events created yet.</p>}</>}{message&&<p className="error">{message}</p>}</section>
}
function Table({registrations}) { return <div className="table"><table><thead><tr><th>Event</th><th>Approval</th><th>Pass</th><th>Check-in</th></tr></thead><tbody>{registrations.map(r=><tr key={r.id}><td>{r.event?.title}</td><td>{r.approval_status}</td><td>{r.qr_pass_type.replaceAll('_',' ')}</td><td>{r.checked_in?'Checked in':'Not checked in'}</td></tr>)}</tbody></table></div> }
